/*
 * Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
 *
 * SPDX-License-Identifier: MIT
 */

/**
 * GENERATED FILE — do not edit by hand.
 *
 * Regenerate with:
 *   projects/hrr/tools/api-matrix/check_matrix.py --emit-cxx \
 *       projects/hrr/tests/integration/hrr_api_matrix_expectations.h
 *
 * Source of truth is the pair api_classes.json (derived from HRR's generator)
 * and api_matrix.yaml (the authored tier and expectation overlay). Generating
 * this header rather than transcribing it is what keeps the Catch2 tests and
 * the matrix reporter from drifting into disagreeing about what an API is
 * supposed to do at replay.
 *
 * Generated 2026-10-01 from 554 HIP APIs.
 */

#pragma once

#include <cstddef>

// Mirrors HrrReplayClass in hrr_test_common.hh. Kept as a plain int so this
// header stays self-contained and can be included in either order.
enum HrrExpectCode {
  kHrrExpectReal = 0,       // a real handler runs: GENERATED, MANUAL or CUSTOM
  kHrrExpectNoop = 1,       // NOOP_PLAYBACK_APIS
  kHrrExpectErrorStub = 2,  // ERROR_STUB_PLAYBACK_APIS
  kHrrExpectHandlerError = 3,  // a real handler runs and returns a HIP error
  kHrrExpectCrash = 4,      // a real handler runs and kills the replay process
  kHrrExpectUnreplayable = 5,  // UNREPLAYABLE_PLAYBACK_APIS: refused by name,
                               // with the reason, instead of being attempted
};

enum HrrAppliesWhen {
  kHrrWhenAlways = 0,          // holds on any part
  kHrrWhenNoImageSupport = 1,  // only where hipDeviceAttributeImageSupport = 0
};

struct HrrApiExpectation {
  const char* api;
  const char* tier;
  int expect;          // HrrExpectCode
  bool payload_loss;   // counted as faithful but cannot replay (section 8.3)
  bool expect_captured;  // false: HIP folds it away before HRR records it
  // The handler is real and works, but for the arguments one of this tier's
  // own workloads records it returns an error. Observing HANDLER_ERROR is
  // then a known failure rather than the API having been reclassified.
  bool handler_error_ok;
  bool skip;           // not assertable from a single-process Catch2 workload
  // Device capability this API's unreachable: declaration was measured under.
  // kHrrWhenAlways for everything that holds on any part. Otherwise the matrix
  // has only ever seen the API on a part with that capability, and on any
  // other one it is unmeasured: whether a texture or array handle can exist is
  // a property of the device, so a declaration taken where none can is not
  // evidence about a part where they can.
  int applies_when;
};

// A tier's workloads and the coverage floor its run must clear.
//
// min_covered is the number of APIs the tier must actually reach for its
// result to mean anything: a tier that exercises fewer than this has lost
// call sites, most likely because a workload started failing early and took
// the rest of its API calls with it. Without the floor, a workload that
// aborted on its second line would report a clean sweep of zero failures.
//
// workloads is null-terminated so the test can walk it without a second count.
struct HrrTierFloor {
  const char* tier;
  int min_covered;
  int gpus;
  bool skip_by_default;
  const char* const* workloads;
};

inline constexpr HrrApiExpectation kHrrApiMatrix[] = {
    {"__hipPopCallConfiguration", "T0", 0, false, true, false, false, 0},
    {"__hipPushCallConfiguration", "T0", 0, false, true, false, false, 0},
    {"__hipRegisterFatBinary", "T0", 0, false, true, false, false, 0},
    {"__hipRegisterFunction", "T0", 0, false, false, false, false, 0},
    {"__hipUnregisterFatBinary", "T0", 0, false, false, false, false, 0},
    {"hipDeviceSynchronize", "T0", 0, false, true, false, false, 0},
    {"hipDrvLaunchKernelEx", "T0", 0, false, true, false, false, 0},
    {"hipEventCreate", "T0", 0, false, true, false, false, 0},
    {"hipEventCreateWithFlags", "T0", 0, false, true, false, false, 0},
    {"hipEventDestroy", "T0", 0, false, true, false, false, 0},
    {"hipEventElapsedTime", "T0", 0, false, true, false, false, 0},
    {"hipEventQuery", "T0", 0, false, true, false, false, 0},
    {"hipEventRecord", "T0", 0, false, true, false, false, 0},
    {"hipEventSynchronize", "T0", 0, false, true, false, false, 0},
    {"hipExtModuleLaunchKernel", "T0", 0, false, false, false, false, 0},
    {"hipFree", "T0", 0, false, true, false, false, 0},
    {"hipFuncGetAttribute", "T0", 1, false, true, false, false, 0},
    {"hipGetFuncBySymbol", "T0", 1, false, true, false, false, 0},
    {"hipGetProcAddress", "T0", 0, false, true, false, false, 0},
    {"hipGraphDestroy", "T0", 1, false, true, false, false, 0},
    {"hipGraphExecDestroy", "T0", 1, false, true, false, false, 0},
    {"hipGraphInstantiate", "T0", 0, false, true, false, false, 0},
    {"hipGraphLaunch", "T0", 0, false, true, false, false, 0},
    {"hipHostFree", "T0", 0, false, true, false, false, 0},
    {"hipHostGetDevicePointer", "T0", 0, false, true, false, false, 0},
    {"hipHostMalloc", "T0", 0, false, true, false, false, 0},
    {"hipHostRegister", "T0", 0, false, true, false, false, 0},
    {"hipHostUnregister", "T0", 0, false, true, false, false, 0},
    {"hipLaunchByPtr", "T0", 0, false, false, false, false, 0},
    {"hipLaunchHostFunc", "T0", 5, false, true, false, false, 0},
    {"hipLaunchKernel", "T0", 0, false, false, false, false, 0},
    {"hipLaunchKernelExC", "T0", 0, false, true, false, false, 0},
    {"hipMalloc", "T0", 0, false, true, false, false, 0},
    {"hipMemGetInfo", "T0", 0, false, true, false, false, 0},
    {"hipMemcpy", "T0", 0, false, true, false, false, 0},
    {"hipMemcpyAsync", "T0", 0, false, true, false, false, 0},
    {"hipMemcpyDtoD", "T0", 0, false, true, false, false, 0},
    {"hipMemcpyDtoH", "T0", 0, false, true, false, false, 0},
    {"hipMemcpyDtoHAsync", "T0", 0, false, true, false, false, 0},
    {"hipMemcpyHtoD", "T0", 0, false, true, false, false, 0},
    {"hipMemcpyHtoDAsync", "T0", 0, false, true, false, false, 0},
    {"hipMemcpyWithStream", "T0", 0, false, true, false, false, 0},
    {"hipMemset", "T0", 0, false, true, false, false, 0},
    {"hipMemsetAsync", "T0", 0, false, true, false, false, 0},
    {"hipMemsetD32", "T0", 0, false, true, false, false, 0},
    {"hipMemsetD32Async", "T0", 0, false, true, false, false, 0},
    {"hipModuleGetFunction", "T0", 0, false, false, false, false, 0},
    {"hipModuleLaunchKernel", "T0", 0, false, true, false, false, 0},
    {"hipModuleLoad", "T0", 0, false, true, false, false, 0},
    {"hipModuleLoadData", "T0", 0, false, true, false, false, 0},
    {"hipModuleLoadDataEx", "T0", 0, false, true, false, false, 0},
    {"hipModuleUnload", "T0", 0, false, true, false, false, 0},
    {"hipPointerGetAttributes", "T0", 0, false, true, false, false, 0},
    {"hipStreamBeginCapture", "T0", 0, false, true, false, false, 0},
    {"hipStreamCreate", "T0", 0, false, true, false, false, 0},
    {"hipStreamCreateWithFlags", "T0", 0, false, true, false, false, 0},
    {"hipStreamCreateWithPriority", "T0", 0, false, true, false, false, 0},
    {"hipStreamDestroy", "T0", 0, false, true, false, false, 0},
    {"hipStreamEndCapture", "T0", 0, false, true, false, false, 0},
    {"hipStreamGetCaptureInfo", "T0", 0, false, true, false, false, 0},
    {"hipStreamGetFlags", "T0", 0, false, true, false, false, 0},
    {"hipStreamGetPriority", "T0", 0, false, true, false, false, 0},
    {"hipStreamIsCapturing", "T0", 0, false, true, false, false, 0},
    {"hipStreamQuery", "T0", 0, false, true, false, false, 0},
    {"hipStreamSynchronize", "T0", 0, false, true, false, false, 0},
    {"hipStreamWaitEvent", "T0", 0, false, true, false, false, 0},
    {"hipThreadExchangeStreamCaptureMode", "T0", 0, false, true, false, false, 0},
    {"hipDestroyExternalMemory", "T1", 0, false, false, false, false, 0},
    {"hipDestroyExternalSemaphore", "T1", 0, false, false, false, false, 0},
    {"hipExternalMemoryGetMappedBuffer", "T1", 0, true, false, false, false, 0},
    {"hipImportExternalMemory", "T1", 0, true, false, false, false, 0},
    {"hipImportExternalSemaphore", "T1", 0, true, false, false, false, 0},
    {"hipIpcCloseMemHandle", "T1", 0, false, false, false, false, 0},
    {"hipIpcGetEventHandle", "T1", 0, false, true, false, true, 0},
    {"hipIpcGetMemHandle", "T1", 0, false, true, false, false, 0},
    {"hipIpcOpenEventHandle", "T1", 0, false, false, false, false, 0},
    {"hipIpcOpenMemHandle", "T1", 0, false, false, false, false, 0},
    {"hipLaunchCooperativeKernelMultiDevice", "T1", 5, false, true, false, false, 0},
    {"hipMemCreate", "T1", 0, false, true, false, false, 0},
    {"hipSignalExternalSemaphoresAsync", "T1", 0, true, false, false, false, 0},
    {"hipStreamBatchMemOp", "T1", 0, false, true, false, false, 0},
    {"hipWaitExternalSemaphoresAsync", "T1", 0, true, false, false, false, 0},
    {"hipDrvGraphExecMemcpyNodeSetParams", "T2", 0, false, true, false, false, 0},
    {"hipDrvGraphExecMemsetNodeSetParams", "T2", 0, false, true, false, false, 0},
    {"hipDrvGraphMemcpyNodeSetParams", "T2", 0, false, true, false, false, 0},
    {"hipFreeHost", "T2", 1, false, true, false, false, 0},
    {"hipGetSymbolAddress", "T2", 0, false, true, false, false, 0},
    {"hipGetSymbolSize", "T2", 0, false, true, false, false, 0},
    {"hipGraphBatchMemOpNodeSetParams", "T2", 0, false, true, false, false, 0},
    {"hipGraphExecBatchMemOpNodeSetParams", "T2", 0, false, true, false, false, 0},
    {"hipGraphExecChildGraphNodeSetParams", "T2", 0, false, true, false, false, 0},
    {"hipGraphExecHostNodeSetParams", "T2", 5, true, true, false, false, 0},
    {"hipGraphExecKernelNodeSetParams", "T2", 0, false, true, false, false, 0},
    {"hipGraphExecMemcpyNodeSetParams", "T2", 0, false, true, false, false, 0},
    {"hipGraphExecMemcpyNodeSetParams1D", "T2", 0, false, true, false, false, 0},
    {"hipGraphExecMemsetNodeSetParams", "T2", 0, false, true, false, false, 0},
    {"hipGraphExecNodeSetParams", "T2", 1, false, true, false, false, 0},
    {"hipGraphExecUpdate", "T2", 1, false, true, false, false, 0},
    {"hipGraphHostNodeSetParams", "T2", 5, true, true, false, false, 0},
    {"hipGraphKernelNodeSetParams", "T2", 0, false, true, false, false, 0},
    {"hipGraphMemcpyNodeSetParams", "T2", 0, false, true, false, false, 0},
    {"hipGraphMemcpyNodeSetParams1D", "T2", 0, false, true, false, false, 0},
    {"hipGraphMemsetNodeSetParams", "T2", 0, false, true, false, false, 0},
    {"hipGraphNodeSetParams", "T2", 1, false, true, false, false, 0},
    {"hipHostAlloc", "T2", 1, false, true, false, false, 0},
    {"hipMallocHost", "T2", 1, false, true, false, false, 0},
    {"hipMemAllocHost", "T2", 1, false, true, false, false, 0},
    {"hipMemcpyFromSymbol", "T2", 1, false, true, false, false, 0},
    {"hipMemcpyFromSymbolAsync", "T2", 1, false, true, false, false, 0},
    {"hipMemcpyToSymbol", "T2", 1, false, true, false, false, 0},
    {"hipMemcpyToSymbolAsync", "T2", 1, false, true, false, false, 0},
    {"hipModuleGetGlobal", "T2", 1, false, true, false, false, 0},
    {"hipModuleLaunchCooperativeKernel", "T2", 0, false, true, false, false, 0},
    {"hipStreamWaitValue32", "T2", 1, false, true, false, false, 0},
    {"hipStreamWaitValue64", "T2", 1, false, true, false, false, 0},
    {"hipStreamWriteValue32", "T2", 0, false, true, false, false, 0},
    {"hipStreamWriteValue64", "T2", 0, false, true, false, false, 0},
    {"hipDeviceCanAccessPeer", "T3", 0, false, true, false, false, 0},
    {"hipDeviceDisablePeerAccess", "T3", 0, false, true, false, false, 0},
    {"hipDeviceEnablePeerAccess", "T3", 0, false, true, false, false, 0},
    {"hipDeviceGetP2PAttribute", "T3", 0, false, true, false, false, 0},
    {"hipExtGetLinkTypeAndHopCount", "T3", 1, false, true, false, false, 0},
    {"hipMemAddressFree", "T3", 0, false, true, false, false, 0},
    {"hipMemAddressReserve", "T3", 0, false, true, false, false, 0},
    {"hipMemExportToShareableHandle", "T3", 0, false, true, false, false, 0},
    {"hipMemGetAccess", "T3", 0, false, true, false, false, 0},
    {"hipMemGetAllocationGranularity", "T3", 0, false, true, false, false, 0},
    {"hipMemGetAllocationPropertiesFromHandle", "T3", 1, false, true, false, false, 0},
    {"hipMemGetHandleForAddressRange", "T3", 0, false, true, false, false, 0},
    {"hipMemImportFromShareableHandle", "T3", 5, false, true, false, false, 0},
    {"hipMemMap", "T3", 0, false, true, false, false, 0},
    {"hipMemRelease", "T3", 0, false, true, false, false, 0},
    {"hipMemRetainAllocationHandle", "T3", 1, false, true, false, false, 0},
    {"hipMemSetAccess", "T3", 0, false, true, false, false, 0},
    {"hipMemUnmap", "T3", 0, false, true, false, false, 0},
    {"hipMemcpy3DPeer", "T3", 1, false, true, false, false, 0},
    {"hipMemcpy3DPeerAsync", "T3", 1, false, true, false, false, 0},
    {"hipMemcpyPeer", "T3", 0, false, true, false, false, 0},
    {"hipMemcpyPeerAsync", "T3", 0, false, true, false, false, 0},
    {"__hipRegisterManagedVar", "T4", 0, false, true, false, false, 0},
    {"__hipRegisterVar", "T4", 0, false, true, false, false, 0},
    {"hipApiName", "T4", 1, false, true, false, false, 0},
    {"hipChooseDevice", "T4", 0, false, true, false, false, 0},
    {"hipChooseDeviceR0000", "T4", 0, false, true, false, false, 0},
    {"hipConfigureCall", "T4", 0, false, true, false, false, 0},
    {"hipCtxCreate", "T4", 0, false, true, false, false, 0},
    {"hipCtxDestroy", "T4", 0, false, true, false, false, 0},
    {"hipCtxDisablePeerAccess", "T4", 1, false, true, false, false, 0},
    {"hipCtxEnablePeerAccess", "T4", 1, false, true, false, false, 0},
    {"hipCtxGetApiVersion", "T4", 1, false, true, false, false, 0},
    {"hipCtxGetCacheConfig", "T4", 1, false, true, false, false, 0},
    {"hipCtxGetCurrent", "T4", 0, false, true, false, false, 0},
    {"hipCtxGetDevice", "T4", 1, false, true, false, false, 0},
    {"hipCtxGetFlags", "T4", 1, false, true, false, false, 0},
    {"hipCtxGetSharedMemConfig", "T4", 1, false, true, false, false, 0},
    {"hipCtxPopCurrent", "T4", 0, false, true, false, false, 0},
    {"hipCtxPushCurrent", "T4", 0, false, true, false, false, 0},
    {"hipCtxSetCacheConfig", "T4", 0, false, true, false, false, 0},
    {"hipCtxSetCurrent", "T4", 1, false, true, false, false, 0},
    {"hipCtxSetSharedMemConfig", "T4", 0, false, true, false, false, 0},
    {"hipCtxSynchronize", "T4", 0, false, true, false, false, 0},
    {"hipDevResourceGenerateDesc", "T4", 0, false, true, false, false, 0},
    {"hipDevSmResourceSplit", "T4", 0, true, true, false, false, 0},
    {"hipDevSmResourceSplitByCount", "T4", 0, true, true, false, false, 0},
    {"hipDeviceComputeCapability", "T4", 0, false, true, false, false, 0},
    {"hipDeviceGet", "T4", 1, false, true, false, false, 0},
    {"hipDeviceGetAttribute", "T4", 0, false, true, false, false, 0},
    {"hipDeviceGetByPCIBusId", "T4", 1, false, true, false, false, 0},
    {"hipDeviceGetCacheConfig", "T4", 0, false, true, false, false, 0},
    {"hipDeviceGetDefaultMemPool", "T4", 0, false, true, false, false, 0},
    {"hipDeviceGetDevResource", "T4", 0, false, true, false, false, 0},
    {"hipDeviceGetExecutionCtx", "T4", 0, false, true, false, false, 0},
    {"hipDeviceGetGraphMemAttribute", "T4", 1, false, true, false, false, 0},
    {"hipDeviceGetLimit", "T4", 0, false, true, false, false, 0},
    {"hipDeviceGetLuid", "T4", 1, false, true, false, false, 0},
    {"hipDeviceGetMemPool", "T4", 0, false, true, false, false, 0},
    {"hipDeviceGetName", "T4", 1, false, true, false, false, 0},
    {"hipDeviceGetPCIBusId", "T4", 1, false, true, false, false, 0},
    {"hipDeviceGetSharedMemConfig", "T4", 0, false, true, false, false, 0},
    {"hipDeviceGetStreamPriorityRange", "T4", 0, false, true, false, false, 0},
    {"hipDeviceGetTexture1DLinearMaxWidth", "T4", 0, false, true, false, false, 0},
    {"hipDeviceGetUuid", "T4", 1, false, true, false, false, 0},
    {"hipDeviceGraphMemTrim", "T4", 0, false, true, false, false, 0},
    {"hipDevicePrimaryCtxGetState", "T4", 1, false, true, false, false, 0},
    {"hipDevicePrimaryCtxRelease", "T4", 1, false, true, false, false, 0},
    {"hipDevicePrimaryCtxReset", "T4", 1, false, true, false, false, 0},
    {"hipDevicePrimaryCtxRetain", "T4", 0, false, true, false, false, 0},
    {"hipDevicePrimaryCtxSetFlags", "T4", 1, false, true, false, false, 0},
    {"hipDeviceReset", "T4", 0, false, true, false, false, 0},
    {"hipDeviceSetCacheConfig", "T4", 0, false, true, false, false, 0},
    {"hipDeviceSetGraphMemAttribute", "T4", 1, false, true, false, false, 0},
    {"hipDeviceSetLimit", "T4", 0, false, true, false, false, 0},
    {"hipDeviceSetMemPool", "T4", 0, false, true, false, false, 0},
    {"hipDeviceSetSharedMemConfig", "T4", 0, false, true, false, false, 0},
    {"hipDeviceTotalMem", "T4", 0, false, true, false, false, 0},
    {"hipDriverGetVersion", "T4", 0, false, true, false, false, 0},
    {"hipDrvGetErrorName", "T4", 1, false, true, false, false, 0},
    {"hipDrvGetErrorString", "T4", 1, false, true, false, false, 0},
    {"hipDrvGraphAddMemFreeNode", "T4", 0, false, true, false, false, 0},
    {"hipDrvGraphAddMemcpyNode", "T4", 0, false, true, false, false, 0},
    {"hipDrvGraphAddMemsetNode", "T4", 0, false, true, false, false, 0},
    {"hipDrvGraphMemcpyNodeGetParams", "T4", 1, false, true, false, false, 0},
    {"hipDrvMemDiscardAndPrefetchBatchAsync", "T4", 1, false, true, false, false, 0},
    {"hipDrvMemDiscardBatchAsync", "T4", 1, false, true, false, false, 0},
    {"hipDrvMemcpy2DUnaligned", "T4", 0, false, true, false, false, 0},
    {"hipDrvMemcpy3D", "T4", 0, false, true, false, false, 0},
    {"hipDrvMemcpy3DAsync", "T4", 0, false, true, false, false, 0},
    {"hipDrvPointerGetAttributes", "T4", 1, false, true, false, false, 0},
    {"hipEventRecordWithFlags", "T4", 0, false, true, false, false, 0},
    {"hipEventRecord_spt", "T4", 0, false, true, false, false, 0},
    {"hipExecutionCtxDestroy", "T4", 0, false, true, false, false, 0},
    {"hipExecutionCtxGetDevResource", "T4", 0, false, true, false, false, 0},
    {"hipExecutionCtxGetDevice", "T4", 0, false, true, false, false, 0},
    {"hipExecutionCtxGetId", "T4", 0, false, true, false, false, 0},
    {"hipExecutionCtxRecordEvent", "T4", 0, false, true, false, false, 0},
    {"hipExecutionCtxStreamCreate", "T4", 0, false, true, false, false, 0},
    {"hipExecutionCtxSynchronize", "T4", 0, false, true, false, false, 0},
    {"hipExecutionCtxWaitEvent", "T4", 0, false, true, false, false, 0},
    {"hipExtDisableLogging", "T4", 0, false, true, false, false, 0},
    {"hipExtEnableLogging", "T4", 0, false, true, false, false, 0},
    {"hipExtGetLastError", "T4", 0, false, true, false, false, 0},
    {"hipExtHostAlloc", "T4", 1, false, true, false, false, 0},
    {"hipExtLaunchMultiKernelMultiDevice", "T4", 5, false, true, false, false, 0},
    {"hipExtMallocWithFlags", "T4", 0, false, true, false, false, 0},
    {"hipExtSetLoggingParams", "T4", 0, false, true, false, false, 0},
    {"hipExtStreamCreateWithCUMask", "T4", 1, false, true, false, false, 0},
    {"hipExtStreamGetCUMask", "T4", 1, false, true, false, false, 0},
    {"hipFreeAsync", "T4", 0, false, true, false, false, 0},
    {"hipFuncGetAttributes", "T4", 1, false, true, false, false, 0},
    {"hipFuncSetAttribute", "T4", 1, false, true, false, false, 0},
    {"hipFuncSetCacheConfig", "T4", 1, false, true, false, false, 0},
    {"hipFuncSetSharedMemConfig", "T4", 1, false, true, false, false, 0},
    {"hipGetDevice", "T4", 0, false, true, false, false, 0},
    {"hipGetDeviceCount", "T4", 0, false, true, false, false, 0},
    {"hipGetDeviceFlags", "T4", 0, false, true, false, false, 0},
    {"hipGetDevicePropertiesR0000", "T4", 1, false, true, false, false, 0},
    {"hipGetDevicePropertiesR0600", "T4", 0, false, true, false, false, 0},
    {"hipGetDriverEntryPoint", "T4", 1, false, true, false, false, 0},
    {"hipGetDriverEntryPoint_spt", "T4", 1, false, true, false, false, 0},
    {"hipGetErrorName", "T4", 1, false, true, false, false, 0},
    {"hipGetErrorString", "T4", 1, false, true, false, false, 0},
    {"hipGetLastError", "T4", 0, false, true, false, false, 0},
    {"hipGetProcAddress_spt", "T4", 0, false, true, false, false, 0},
    {"hipGetStreamDeviceId", "T4", 1, false, true, false, false, 0},
    {"hipGetTextureObjectResourceDesc", "T4", 0, false, true, false, false, 1},
    {"hipGetTextureObjectResourceViewDesc", "T4", 0, false, true, false, false, 1},
    {"hipGetTextureObjectTextureDesc", "T4", 0, false, true, false, false, 1},
    {"hipGraphAddBatchMemOpNode", "T4", 0, false, true, false, false, 0},
    {"hipGraphAddChildGraphNode", "T4", 0, false, true, false, false, 0},
    {"hipGraphAddDependencies", "T4", 0, false, true, false, false, 0},
    {"hipGraphAddEmptyNode", "T4", 0, false, true, false, false, 0},
    {"hipGraphAddEventRecordNode", "T4", 0, false, true, false, false, 0},
    {"hipGraphAddEventWaitNode", "T4", 0, false, true, false, false, 0},
    {"hipGraphAddExternalSemaphoresSignalNode", "T4", 2, true, true, false, false, 0},
    {"hipGraphAddExternalSemaphoresWaitNode", "T4", 2, true, true, false, false, 0},
    {"hipGraphAddHostNode", "T4", 5, true, true, false, false, 0},
    {"hipGraphAddKernelNode", "T4", 0, false, true, false, false, 0},
    {"hipGraphAddMemAllocNode", "T4", 0, false, true, false, false, 0},
    {"hipGraphAddMemFreeNode", "T4", 0, false, true, false, false, 0},
    {"hipGraphAddMemcpyNode", "T4", 0, false, true, false, false, 0},
    {"hipGraphAddMemcpyNode1D", "T4", 0, false, true, false, false, 0},
    {"hipGraphAddMemcpyNodeFromSymbol", "T4", 0, false, true, false, false, 0},
    {"hipGraphAddMemcpyNodeToSymbol", "T4", 0, false, true, false, false, 0},
    {"hipGraphAddMemsetNode", "T4", 0, false, true, false, false, 0},
    {"hipGraphAddNode", "T4", 2, false, true, false, false, 0},
    {"hipGraphBatchMemOpNodeGetParams", "T4", 1, false, true, false, false, 0},
    {"hipGraphChildGraphNodeGetGraph", "T4", 1, false, true, false, false, 0},
    {"hipGraphClone", "T4", 0, false, true, false, false, 0},
    {"hipGraphCreate", "T4", 0, false, true, false, false, 0},
    {"hipGraphDebugDotPrint", "T4", 1, false, true, false, false, 0},
    {"hipGraphDestroyNode", "T4", 0, false, true, false, false, 0},
    {"hipGraphEventRecordNodeGetEvent", "T4", 1, false, true, false, false, 0},
    {"hipGraphEventRecordNodeSetEvent", "T4", 0, false, true, false, false, 0},
    {"hipGraphEventWaitNodeGetEvent", "T4", 1, false, true, false, false, 0},
    {"hipGraphEventWaitNodeSetEvent", "T4", 0, false, true, false, false, 0},
    {"hipGraphExecEventRecordNodeSetEvent", "T4", 0, false, true, false, false, 0},
    {"hipGraphExecEventWaitNodeSetEvent", "T4", 0, false, true, false, false, 0},
    {"hipGraphExecExternalSemaphoresSignalNodeSetParams", "T4", 0, true, true, false, false, 0},
    {"hipGraphExecExternalSemaphoresWaitNodeSetParams", "T4", 0, true, true, false, false, 0},
    {"hipGraphExecGetFlags", "T4", 1, false, true, false, false, 0},
    {"hipGraphExecMemcpyNodeSetParamsFromSymbol", "T4", 0, false, true, true, false, 0},
    {"hipGraphExecMemcpyNodeSetParamsToSymbol", "T4", 0, false, true, true, false, 0},
    {"hipGraphExternalSemaphoresSignalNodeGetParams", "T4", 0, false, true, false, false, 0},
    {"hipGraphExternalSemaphoresSignalNodeSetParams", "T4", 0, true, true, false, false, 0},
    {"hipGraphExternalSemaphoresWaitNodeGetParams", "T4", 0, false, true, false, false, 0},
    {"hipGraphExternalSemaphoresWaitNodeSetParams", "T4", 0, true, true, false, false, 0},
    {"hipGraphGetEdges", "T4", 1, false, true, false, false, 0},
    {"hipGraphGetNodes", "T4", 1, false, true, false, false, 0},
    {"hipGraphGetRootNodes", "T4", 1, false, true, false, false, 0},
    {"hipGraphHostNodeGetParams", "T4", 1, false, true, false, false, 0},
    {"hipGraphInstantiateWithFlags", "T4", 0, false, true, false, false, 0},
    {"hipGraphInstantiateWithParams", "T4", 2, false, true, false, false, 0},
    {"hipGraphKernelNodeCopyAttributes", "T4", 0, false, true, false, false, 0},
    {"hipGraphKernelNodeGetAttribute", "T4", 1, false, true, false, false, 0},
    {"hipGraphKernelNodeGetParams", "T4", 1, false, true, false, false, 0},
    {"hipGraphKernelNodeSetAttribute", "T4", 0, false, true, false, false, 0},
    {"hipGraphLaunch_spt", "T4", 0, false, true, false, false, 0},
    {"hipGraphMemAllocNodeGetParams", "T4", 1, false, true, false, false, 0},
    {"hipGraphMemFreeNodeGetParams", "T4", 1, false, true, false, false, 0},
    {"hipGraphMemcpyNodeGetParams", "T4", 1, false, true, false, false, 0},
    {"hipGraphMemcpyNodeSetParamsFromSymbol", "T4", 0, false, true, false, false, 0},
    {"hipGraphMemcpyNodeSetParamsToSymbol", "T4", 0, false, true, false, false, 0},
    {"hipGraphMemsetNodeGetParams", "T4", 1, false, true, false, false, 0},
    {"hipGraphNodeFindInClone", "T4", 0, false, true, false, false, 0},
    {"hipGraphNodeGetDependencies", "T4", 1, false, true, false, false, 0},
    {"hipGraphNodeGetDependentNodes", "T4", 1, false, true, false, false, 0},
    {"hipGraphNodeGetEnabled", "T4", 1, false, true, false, false, 0},
    {"hipGraphNodeGetType", "T4", 1, false, true, false, false, 0},
    {"hipGraphNodeSetEnabled", "T4", 0, false, true, false, false, 0},
    {"hipGraphReleaseUserObject", "T4", 1, false, true, false, false, 0},
    {"hipGraphRemoveDependencies", "T4", 1, false, true, false, false, 0},
    {"hipGraphRetainUserObject", "T4", 1, false, true, false, false, 0},
    {"hipGraphUpload", "T4", 1, false, true, false, false, 0},
    {"hipGreenCtxCreate", "T4", 0, false, true, false, false, 0},
    {"hipHccModuleLaunchKernel", "T4", 1, false, true, false, false, 0},
    {"hipHostGetFlags", "T4", 1, false, true, false, false, 0},
    {"hipInit", "T4", 0, false, true, false, false, 0},
    {"hipInitDevice", "T4", 1, false, true, false, false, 0},
    {"hipKernelGetAttribute", "T4", 1, false, true, false, false, 0},
    {"hipKernelGetFunction", "T4", 1, false, true, false, false, 0},
    {"hipKernelGetLibrary", "T4", 1, false, true, false, false, 0},
    {"hipKernelGetName", "T4", 1, false, true, false, false, 0},
    {"hipKernelGetParamInfo", "T4", 1, false, true, false, false, 0},
    {"hipKernelNameRef", "T4", 1, false, true, false, false, 0},
    {"hipKernelNameRefByPtr", "T4", 1, false, true, false, false, 0},
    {"hipKernelSetAttribute", "T4", 1, false, true, false, false, 0},
    {"hipLaunchCooperativeKernel_spt", "T4", 0, false, true, false, false, 0},
    {"hipLaunchHostFunc_spt", "T4", 5, false, true, false, false, 0},
    {"hipLaunchKernel_spt", "T4", 0, false, true, false, false, 0},
    {"hipLibraryEnumerateKernels", "T4", 1, false, true, false, false, 0},
    {"hipLibraryGetGlobal", "T4", 0, false, true, false, false, 0},
    {"hipLibraryGetKernel", "T4", 1, false, true, false, false, 0},
    {"hipLibraryGetKernelCount", "T4", 1, false, true, false, false, 0},
    {"hipLibraryGetManaged", "T4", 0, false, true, false, false, 0},
    {"hipLibraryLoadData", "T4", 1, false, true, false, false, 0},
    {"hipLibraryLoadFromFile", "T4", 1, false, true, false, false, 0},
    {"hipLibraryUnload", "T4", 1, false, true, false, false, 0},
    {"hipLinkAddData", "T4", 0, false, true, false, false, 0},
    {"hipLinkAddFile", "T4", 0, false, true, false, false, 0},
    {"hipLinkComplete", "T4", 0, false, true, false, false, 0},
    {"hipLinkCreate", "T4", 0, false, true, false, false, 0},
    {"hipLinkDestroy", "T4", 0, false, true, false, false, 0},
    {"hipMalloc3D", "T4", 1, false, true, false, false, 0},
    {"hipMallocAsync", "T4", 0, false, true, false, false, 0},
    {"hipMallocFromPoolAsync", "T4", 0, false, true, false, false, 0},
    {"hipMallocPitch", "T4", 0, false, true, false, false, 0},
    {"hipMemAllocPitch", "T4", 1, false, true, false, false, 0},
    {"hipMemDiscardAndPrefetchBatchAsync", "T4", 1, false, true, false, false, 0},
    {"hipMemDiscardBatchAsync", "T4", 1, false, true, false, false, 0},
    {"hipMemGetAddressRange", "T4", 1, false, true, false, false, 0},
    {"hipMemGetDefaultMemPool", "T4", 1, false, true, false, false, 0},
    {"hipMemGetMemPool", "T4", 0, false, true, false, false, 0},
    {"hipMemPoolCreate", "T4", 0, false, true, false, false, 0},
    {"hipMemPoolDestroy", "T4", 0, false, true, false, false, 0},
    {"hipMemPoolExportPointer", "T4", 1, false, true, false, false, 0},
    {"hipMemPoolExportToShareableHandle", "T4", 0, false, true, false, false, 0},
    {"hipMemPoolGetAccess", "T4", 1, false, true, false, false, 0},
    {"hipMemPoolGetAttribute", "T4", 0, false, true, false, false, 0},
    {"hipMemPoolImportFromShareableHandle", "T4", 5, false, true, false, false, 0},
    {"hipMemPoolImportPointer", "T4", 1, false, true, false, false, 0},
    {"hipMemPoolSetAccess", "T4", 0, false, true, false, false, 0},
    {"hipMemPoolSetAttribute", "T4", 0, false, true, false, false, 0},
    {"hipMemPoolTrimTo", "T4", 0, false, true, false, false, 0},
    {"hipMemPrefetchBatchAsync", "T4", 0, false, true, false, false, 0},
    {"hipMemPtrGetInfo", "T4", 1, false, true, false, false, 0},
    {"hipMemSetMemPool", "T4", 0, false, true, false, false, 0},
    {"hipMemcpy2D", "T4", 0, false, true, false, false, 0},
    {"hipMemcpy2DAsync", "T4", 0, false, true, false, false, 0},
    {"hipMemcpy2DAsync_spt", "T4", 1, false, true, false, false, 0},
    {"hipMemcpy2D_spt", "T4", 1, false, true, false, false, 0},
    {"hipMemcpy3D", "T4", 0, false, true, false, false, 0},
    {"hipMemcpy3DAsync", "T4", 0, false, true, false, false, 0},
    {"hipMemcpy3DAsync_spt", "T4", 0, false, true, false, false, 0},
    {"hipMemcpy3DBatchAsync", "T4", 0, false, true, false, false, 0},
    {"hipMemcpy3D_spt", "T4", 0, false, true, false, false, 0},
    {"hipMemcpyAsync_spt", "T4", 1, false, true, false, false, 0},
    {"hipMemcpyAtoA", "T4", 1, false, true, false, false, 1},
    {"hipMemcpyAtoD", "T4", 1, false, true, false, false, 1},
    {"hipMemcpyAtoH", "T4", 1, false, true, false, false, 1},
    {"hipMemcpyAtoHAsync", "T4", 1, false, true, false, false, 1},
    {"hipMemcpyBatchAsync", "T4", 0, false, true, false, false, 0},
    {"hipMemcpyDtoA", "T4", 1, false, true, false, false, 1},
    {"hipMemcpyDtoDAsync", "T4", 0, false, true, false, false, 0},
    {"hipMemcpyFromSymbolAsync_spt", "T4", 1, false, true, false, false, 0},
    {"hipMemcpyFromSymbol_spt", "T4", 1, false, true, false, false, 0},
    {"hipMemcpyHtoA", "T4", 1, false, true, false, false, 1},
    {"hipMemcpyHtoAAsync", "T4", 1, false, true, false, false, 1},
    {"hipMemcpyParam2D", "T4", 0, false, true, false, false, 0},
    {"hipMemcpyParam2DAsync", "T4", 0, false, true, false, false, 0},
    {"hipMemcpyToSymbolAsync_spt", "T4", 1, false, true, false, false, 0},
    {"hipMemcpyToSymbol_spt", "T4", 1, false, true, false, false, 0},
    {"hipMemcpy_spt", "T4", 1, false, true, false, false, 0},
    {"hipMemset2D", "T4", 0, false, true, false, false, 0},
    {"hipMemset2DAsync", "T4", 0, false, true, false, false, 0},
    {"hipMemset2DAsync_spt", "T4", 0, false, true, false, false, 0},
    {"hipMemset2D_spt", "T4", 0, false, true, false, false, 0},
    {"hipMemset3D", "T4", 1, false, true, false, false, 0},
    {"hipMemset3DAsync", "T4", 1, false, true, false, false, 0},
    {"hipMemset3DAsync_spt", "T4", 1, false, true, false, false, 0},
    {"hipMemset3D_spt", "T4", 1, false, true, false, false, 0},
    {"hipMemsetAsync_spt", "T4", 0, false, true, false, false, 0},
    {"hipMemsetD16", "T4", 0, false, true, false, false, 0},
    {"hipMemsetD16Async", "T4", 0, false, true, false, false, 0},
    {"hipMemsetD2D16", "T4", 0, false, true, false, false, 0},
    {"hipMemsetD2D16Async", "T4", 0, false, true, false, false, 0},
    {"hipMemsetD2D32", "T4", 0, false, true, false, false, 0},
    {"hipMemsetD2D32Async", "T4", 0, false, true, false, false, 0},
    {"hipMemsetD2D8", "T4", 0, false, true, false, false, 0},
    {"hipMemsetD2D8Async", "T4", 0, false, true, false, false, 0},
    {"hipMemsetD8", "T4", 0, false, true, false, false, 0},
    {"hipMemsetD8Async", "T4", 0, false, true, false, false, 0},
    {"hipMemset_spt", "T4", 0, false, true, false, false, 0},
    {"hipModuleEnumerateFunctions", "T4", 1, false, true, false, false, 0},
    {"hipModuleGetFunctionCount", "T4", 1, false, true, false, false, 0},
    {"hipModuleGetTexRef", "T4", 1, false, true, false, false, 1},
    {"hipModuleLaunchCooperativeKernelMultiDevice", "T4", 0, false, true, false, false, 0},
    {"hipModuleLoadFatBinary", "T4", 1, false, true, false, false, 0},
    {"hipModuleOccupancyMaxActiveBlocksPerMultiprocessor", "T4", 1, false, true, false, false, 0},
    {"hipModuleOccupancyMaxActiveBlocksPerMultiprocessorWithFlags", "T4", 1, false, true, false, false, 0},
    {"hipModuleOccupancyMaxPotentialBlockSize", "T4", 1, false, true, false, false, 0},
    {"hipModuleOccupancyMaxPotentialBlockSizeWithFlags", "T4", 1, false, true, false, false, 0},
    {"hipOccupancyAvailableDynamicSMemPerBlock", "T4", 1, false, true, false, false, 0},
    {"hipOccupancyMaxActiveBlocksPerMultiprocessor", "T4", 1, false, true, false, false, 0},
    {"hipOccupancyMaxActiveBlocksPerMultiprocessorWithFlags", "T4", 1, false, true, false, false, 0},
    {"hipOccupancyMaxActiveClusters", "T4", 1, true, true, false, false, 0},
    {"hipOccupancyMaxPotentialBlockSize", "T4", 1, false, true, false, false, 0},
    {"hipOccupancyMaxPotentialClusterSize", "T4", 1, true, true, false, false, 0},
    {"hipPeekAtLastError", "T4", 0, false, true, false, false, 0},
    {"hipPointerGetAttribute", "T4", 1, false, true, false, false, 0},
    {"hipPointerSetAttribute", "T4", 1, false, true, false, false, 0},
    {"hipProfilerStart", "T4", 0, false, true, false, false, 0},
    {"hipProfilerStop", "T4", 0, false, true, false, false, 0},
    {"hipRuntimeGetVersion", "T4", 0, false, true, false, false, 0},
    {"hipSetDevice", "T4", 0, false, true, false, false, 0},
    {"hipSetDeviceFlags", "T4", 0, false, true, false, false, 0},
    {"hipSetValidDevices", "T4", 1, false, true, false, false, 0},
    {"hipSetupArgument", "T4", 0, false, true, false, false, 0},
    {"hipStreamAddCallback", "T4", 5, false, true, false, false, 0},
    {"hipStreamAddCallback_spt", "T4", 5, false, true, false, false, 0},
    {"hipStreamAttachMemAsync", "T4", 1, false, true, false, false, 0},
    {"hipStreamBeginCaptureToGraph", "T4", 0, false, true, false, false, 0},
    {"hipStreamBeginCapture_spt", "T4", 0, false, true, false, false, 0},
    {"hipStreamCopyAttributes", "T4", 0, false, true, false, false, 0},
    {"hipStreamEndCapture_spt", "T4", 0, false, true, false, false, 0},
    {"hipStreamGetAttribute", "T4", 0, false, true, false, false, 0},
    {"hipStreamGetCaptureInfo_spt", "T4", 0, false, true, false, false, 0},
    {"hipStreamGetCaptureInfo_v2", "T4", 1, false, true, false, false, 0},
    {"hipStreamGetCaptureInfo_v2_spt", "T4", 1, false, true, false, false, 0},
    {"hipStreamGetDevResource", "T4", 0, false, true, false, false, 0},
    {"hipStreamGetDevice", "T4", 1, false, true, false, false, 0},
    {"hipStreamGetFlags_spt", "T4", 0, false, true, false, false, 0},
    {"hipStreamGetId", "T4", 0, false, true, false, false, 0},
    {"hipStreamGetPriority_spt", "T4", 0, false, true, false, false, 0},
    {"hipStreamIsCapturing_spt", "T4", 0, false, true, false, false, 0},
    {"hipStreamQuery_spt", "T4", 0, false, true, false, false, 0},
    {"hipStreamSetAttribute", "T4", 0, false, true, false, false, 0},
    {"hipStreamSynchronize_spt", "T4", 0, false, true, false, false, 0},
    {"hipStreamUpdateCaptureDependencies", "T4", 1, false, true, false, false, 0},
    {"hipStreamWaitEvent_spt", "T4", 0, false, true, false, false, 0},
    {"hipUserObjectCreate", "T4", 5, true, true, false, false, 0},
    {"hipUserObjectRelease", "T4", 1, false, true, false, false, 0},
    {"hipUserObjectRetain", "T4", 1, false, true, false, false, 0},
    {"__hipRegisterSurface", "T5", 0, false, true, false, false, 0},
    {"__hipRegisterTexture", "T5", 0, false, true, false, false, 0},
    {"hipArray3DCreate", "T5", 0, false, true, false, false, 1},
    {"hipArray3DGetDescriptor", "T5", 1, false, true, false, false, 1},
    {"hipArrayCreate", "T5", 0, false, true, false, false, 1},
    {"hipArrayDestroy", "T5", 1, false, true, false, false, 1},
    {"hipArrayGetDescriptor", "T5", 1, false, true, false, false, 1},
    {"hipArrayGetInfo", "T5", 1, false, true, false, false, 1},
    {"hipBindTexture", "T5", 0, true, true, false, false, 1},
    {"hipBindTexture2D", "T5", 0, true, true, false, false, 1},
    {"hipBindTextureToArray", "T5", 0, true, true, false, false, 1},
    {"hipBindTextureToMipmappedArray", "T5", 0, true, true, false, false, 1},
    {"hipCreateChannelDesc", "T5", 1, false, true, false, false, 1},
    {"hipCreateSurfaceObject", "T5", 0, true, true, false, false, 1},
    {"hipCreateTextureObject", "T5", 1, true, true, false, false, 1},
    {"hipDestroySurfaceObject", "T5", 0, false, true, false, false, 0},
    {"hipDestroyTextureObject", "T5", 1, false, true, false, false, 0},
    {"hipExtLaunchKernel", "T5", 1, false, true, false, false, 0},
    {"hipExternalMemoryGetMappedMipmappedArray", "T5", 0, true, true, false, false, 1},
    {"hipFreeArray", "T5", 0, false, true, false, false, 1},
    {"hipFreeMipmappedArray", "T5", 1, false, true, false, false, 1},
    {"hipGLGetDevices", "T5", 1, false, true, false, false, 0},
    {"hipGetChannelDesc", "T5", 1, false, true, false, false, 1},
    {"hipGetMipmappedArrayLevel", "T5", 1, false, true, false, false, 1},
    {"hipGetTextureAlignmentOffset", "T5", 0, true, true, false, false, 1},
    {"hipGetTextureReference", "T5", 1, false, true, false, false, 1},
    {"hipGraphicsGLRegisterBuffer", "T5", 1, false, true, false, false, 0},
    {"hipGraphicsGLRegisterImage", "T5", 1, false, true, false, false, 0},
    {"hipGraphicsMapResources", "T5", 0, false, true, false, false, 0},
    {"hipGraphicsResourceGetMappedPointer", "T5", 0, true, true, false, false, 0},
    {"hipGraphicsSubResourceGetMappedArray", "T5", 0, true, true, false, false, 0},
    {"hipGraphicsUnmapResources", "T5", 0, false, true, false, false, 0},
    {"hipGraphicsUnregisterResource", "T5", 0, true, true, false, false, 0},
    {"hipLaunchCooperativeKernel", "T5", 0, false, true, false, false, 0},
    {"hipMalloc3DArray", "T5", 1, true, true, false, false, 1},
    {"hipMallocArray", "T5", 1, true, true, false, false, 1},
    {"hipMallocManaged", "T5", 0, false, true, false, false, 0},
    {"hipMallocMipmappedArray", "T5", 1, true, true, false, false, 1},
    {"hipMemAdvise", "T5", 0, false, true, false, false, 0},
    {"hipMemAdvise_v2", "T5", 0, false, true, false, false, 0},
    {"hipMemMapArrayAsync", "T5", 1, false, true, false, false, 1},
    {"hipMemPrefetchAsync", "T5", 0, false, true, false, false, 0},
    {"hipMemPrefetchAsync_v2", "T5", 0, false, true, false, false, 0},
    {"hipMemRangeGetAttribute", "T5", 1, false, true, false, false, 0},
    {"hipMemRangeGetAttributes", "T5", 1, false, true, false, false, 0},
    {"hipMemcpy2DArrayToArray", "T5", 1, false, true, false, false, 1},
    {"hipMemcpy2DFromArray", "T5", 1, false, true, false, false, 1},
    {"hipMemcpy2DFromArrayAsync", "T5", 1, false, true, false, false, 1},
    {"hipMemcpy2DFromArrayAsync_spt", "T5", 1, false, true, false, false, 1},
    {"hipMemcpy2DFromArray_spt", "T5", 1, false, true, false, false, 1},
    {"hipMemcpy2DToArray", "T5", 1, false, true, false, false, 1},
    {"hipMemcpy2DToArrayAsync", "T5", 1, false, true, false, false, 1},
    {"hipMemcpy2DToArrayAsync_spt", "T5", 1, false, true, false, false, 1},
    {"hipMemcpy2DToArray_spt", "T5", 1, false, true, false, false, 1},
    {"hipMemcpyFromArray", "T5", 1, false, true, false, false, 1},
    {"hipMemcpyFromArray_spt", "T5", 1, false, true, false, false, 1},
    {"hipMemcpyToArray", "T5", 1, false, true, false, false, 1},
    {"hipMipmappedArrayCreate", "T5", 1, false, true, false, false, 1},
    {"hipMipmappedArrayDestroy", "T5", 1, false, true, false, false, 1},
    {"hipMipmappedArrayGetLevel", "T5", 1, false, true, false, false, 1},
    {"hipMipmappedArrayGetMemoryRequirements", "T5", 1, false, true, false, false, 1},
    {"hipTexObjectCreate", "T5", 1, true, true, false, false, 1},
    {"hipTexObjectDestroy", "T5", 1, false, true, false, false, 0},
    {"hipTexObjectGetResourceDesc", "T5", 0, false, true, false, false, 1},
    {"hipTexObjectGetResourceViewDesc", "T5", 0, false, true, false, false, 1},
    {"hipTexObjectGetTextureDesc", "T5", 0, false, true, false, false, 1},
    {"hipTexRefGetAddress", "T5", 1, true, true, false, false, 1},
    {"hipTexRefGetAddressMode", "T5", 0, true, true, false, false, 1},
    {"hipTexRefGetArray", "T5", 0, true, true, false, false, 1},
    {"hipTexRefGetBorderColor", "T5", 0, true, true, false, false, 1},
    {"hipTexRefGetFilterMode", "T5", 0, true, true, false, false, 1},
    {"hipTexRefGetFlags", "T5", 0, true, true, false, false, 1},
    {"hipTexRefGetFormat", "T5", 1, true, true, false, false, 1},
    {"hipTexRefGetMaxAnisotropy", "T5", 0, true, true, false, false, 1},
    {"hipTexRefGetMipMappedArray", "T5", 0, true, true, false, false, 1},
    {"hipTexRefGetMipmapFilterMode", "T5", 0, true, true, false, false, 1},
    {"hipTexRefGetMipmapLevelBias", "T5", 0, true, true, false, false, 1},
    {"hipTexRefGetMipmapLevelClamp", "T5", 0, true, true, false, false, 1},
    {"hipTexRefSetAddress", "T5", 0, false, true, false, false, 1},
    {"hipTexRefSetAddress2D", "T5", 0, true, true, false, false, 1},
    {"hipTexRefSetAddressMode", "T5", 0, false, true, false, false, 1},
    {"hipTexRefSetArray", "T5", 0, false, true, false, false, 1},
    {"hipTexRefSetBorderColor", "T5", 0, false, true, false, false, 1},
    {"hipTexRefSetFilterMode", "T5", 0, false, true, false, false, 1},
    {"hipTexRefSetFlags", "T5", 0, false, true, false, false, 1},
    {"hipTexRefSetFormat", "T5", 1, false, true, false, false, 1},
    {"hipTexRefSetMaxAnisotropy", "T5", 0, false, true, false, false, 1},
    {"hipTexRefSetMipmapFilterMode", "T5", 0, false, true, false, false, 1},
    {"hipTexRefSetMipmapLevelBias", "T5", 0, false, true, false, false, 1},
    {"hipTexRefSetMipmapLevelClamp", "T5", 0, false, true, false, false, 1},
    {"hipTexRefSetMipmappedArray", "T5", 0, false, true, false, false, 1},
    {"hipUnbindTexture", "T5", 0, true, true, false, false, 1},
};

inline constexpr size_t kHrrApiMatrixCount =
    sizeof(kHrrApiMatrix) / sizeof(kHrrApiMatrix[0]);

inline constexpr const char* const kHrrWorkloadsT0[] = {
    "Unit_HRR_ApiMatrix_UC1Dense_Direct",
    nullptr,
};

inline constexpr const char* const kHrrWorkloadsT1[] = {
    "Unit_HRR_ApiMatrix_PayloadLoss_Direct",
    nullptr,
};

inline constexpr const char* const kHrrWorkloadsT2[] = {
    "Unit_HRR_ApiMatrix_SilentFailure_Direct",
    nullptr,
};

inline constexpr const char* const kHrrWorkloadsT3[] = {
    "Unit_HRR_ApiMatrix_MultiGpu_Direct",
    "Unit_HRR_ApiMatrix_ShareableHandle_Direct",
    "Unit_HRR_MemcpyPeer_Direct",
    "Unit_HRR_VMM_Direct",
    nullptr,
};

inline constexpr const char* const kHrrWorkloadsT4[] = {
    "Unit_HRR_ApiMatrix_Breadth_Direct",
    "Unit_HRR_ApiMatrix_Breadth2_Direct",
    "Unit_HRR_ApiMatrix_Reset_Direct",
    "Unit_HRR_ApiMatrix_GraphNodes_Direct",
    "Unit_HRR_ApiMatrix_LegacySurface_Direct",
    "Unit_HRR_ApiMatrix_LegacyCtx_Direct",
    "Unit_HRR_ApiMatrix_LegacyLaunch_Direct",
    "Unit_HRR_ApiMatrix_ProcAddress_Direct",
    "Unit_HRR_ApiMatrix_SptKernelLaunch_Direct",
    "Unit_HRR_ApiMatrix_SptCoopLaunch_Direct",
    "Unit_HRR_MemcpySpt_Direct",
    "Unit_HRR_MemsetSpt_Direct",
    "Unit_HRR_Memset3DSpt_Direct",
    "Unit_HRR_Memcpy3DSpt_Direct",
    "Unit_HRR_StreamQuerySpt_Direct",
    "Unit_HRR_StreamWaitEventSpt_Direct",
    "Unit_HRR_StreamCaptureBeginSpt_Direct",
    "Unit_HRR_GraphLaunchSpt_Direct",
    "Unit_HRR_StreamCaptureQuerySpt_Direct",
    "Unit_HRR_ApiMatrix_MemPoolShare_Direct",
    "Unit_HRR_AllApis_Direct",
    "Unit_HRR_StressApis_Direct",
    "Unit_HRR_DeviceInfo_Direct",
    "Unit_HRR_DeviceExtra_Direct",
    "Unit_HRR_DeviceMemPool_Direct",
    "Unit_HRR_MemPoolExtended_Direct",
    "Unit_HRR_MemcpyExtra_Direct",
    "Unit_HRR_MemsetExtra_Direct",
    "Unit_HRR_MemsetVariants_Direct",
    "Unit_HRR_DrvMemcpy_Direct",
    "Unit_HRR_DrvMemcpy3D_Direct",
    "Unit_HRR_ModuleAPI_Direct",
    "Unit_HRR_ModuleExtra_Direct",
    "Unit_HRR_StreamAdvanced_Direct",
    "Unit_HRR_StreamAdvanced2_Direct",
    "Unit_HRR_GraphExplicit_Direct",
    "Unit_HRR_GraphWorkload_Direct",
    "Unit_HRR_Occupancy_Direct",
    "Unit_HRR_Context_Direct",
    "Unit_HRR_MiscAPIs_Direct",
    "Unit_HRR_HostAliases_Direct",
    "Unit_HRR_ExtMalloc_Direct",
    "Unit_HRR_Logging_Direct",
    nullptr,
};

inline constexpr const char* const kHrrWorkloadsT5[] = {
    "Unit_HRR_ApiMatrix_Deprioritised_Direct",
    "Unit_HRR_Texture_Direct",
    nullptr,
};

inline constexpr HrrTierFloor kHrrTierFloors[] = {
    {"T0", 65, 1, false, kHrrWorkloadsT0},
    {"T1", 14, 1, false, kHrrWorkloadsT1},
    {"T2", 34, 1, false, kHrrWorkloadsT2},
    {"T3", 20, 2, false, kHrrWorkloadsT3},
    {"T4", 254, 1, false, kHrrWorkloadsT4},
    {"T5", 12, 1, true, kHrrWorkloadsT5},
};

inline constexpr size_t kHrrTierFloorCount =
    sizeof(kHrrTierFloors) / sizeof(kHrrTierFloors[0]);
